import { Runware } from "npm:@runware/sdk-js";

// CORS headers
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE',
  'Access-Control-Max-Age': '86400'
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { synthData, teamData, runwareApiKey, imageType } = await req.json();

    if (!runwareApiKey) {
      return new Response(JSON.stringify({
        error: 'Runware API key is required'
      }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Determine image type and validate required data
    let prompt: string;
    let logName: string;
    let responseKey: string;

    if (imageType === 'team' || teamData) {
      // Team image generation
      if (!teamData || !teamData.name) {
        return new Response(JSON.stringify({
          error: 'Team data with name is required for team image generation'
        }), {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      const teamType = teamData.teamType || 'team';
      const memberCount = teamData.members?.length || 3;
      
      prompt = `Professional group photo of ${teamData.name}, ${teamType === 'team' ? 'collaborative business team working together' : 'diverse group of professionals'}, ${memberCount} people, modern office setting, high quality photography, professional lighting, business attire, diverse ethnicity, team meeting scene`;
      logName = teamData.name;
      responseKey = 'teamImage';
    } else {
      // Synth image generation
      if (!synthData || !synthData.name || !synthData.age || !synthData.role) {
        return new Response(JSON.stringify({
          error: 'Synth data with name, age, and role is required for synth image generation'
        }), {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }

      prompt = `Professional portrait photo of ${synthData.name}, a ${synthData.age}-year-old ${synthData.role}, high quality photography, professional headshot, studio lighting, clean background, photorealistic, detailed face, business professional style`;
      logName = synthData.name;
      responseKey = 'profileImage';
    }

    console.log(`🎨 [BACKGROUND IMAGE GEN] Starting ${imageType || 'synth'} image generation for: ${logName}`);
    console.log(`🖼️ Image prompt: ${prompt}`);

    // Initialize Runware SDK
    const runware = new Runware({ apiKey: runwareApiKey });

    // Generate image using SDK
    const images = await runware.requestImages({
      positivePrompt: prompt,
      negativePrompt: "low quality, blurry, distorted, cartoon, anime, illustration, text, watermark, signature, logo, bad anatomy, deformed, unprofessional, casual clothing",
      width: 1024,
      height: 1024,
      model: "runware:100@1",
      numberResults: 1,
      outputType: "base64Data",
      outputFormat: "PNG",
      steps: 25,
      CFGScale: 7,
      checkNSFW: true
    });

    console.log('🔍 Runware response:', images);

    if (!images || !Array.isArray(images) || images.length === 0) {
      throw new Error('No images generated by Runware API');
    }

    const imageResult = images[0];
    
    if (!imageResult.imageBase64Data && !imageResult.imageURL) {
      throw new Error('No image data received from Runware API');
    }

    // Use base64 data if available, otherwise fetch from URL
    let imageDataUrl: string;
    
    if (imageResult.imageBase64Data) {
      imageDataUrl = `data:image/png;base64,${imageResult.imageBase64Data}`;
    } else if (imageResult.imageURL) {
      // Fetch the image and convert to base64
      const imageResponse = await fetch(imageResult.imageURL);
      const imageArrayBuffer = await imageResponse.arrayBuffer();
      const imageBase64 = btoa(String.fromCharCode(...new Uint8Array(imageArrayBuffer)));
      imageDataUrl = `data:image/png;base64,${imageBase64}`;
    } else {
      throw new Error('No valid image data available');
    }

    console.log(`✅ Successfully generated ${imageType || 'synth'} image for: ${logName}`);

    // Build response based on image type
    const response: any = {
      success: true,
      [responseKey]: imageDataUrl,
      cost: imageResult.cost || 0,
      taskUUID: imageResult.taskUUID || null
    };

    // Add specific IDs based on type
    if (imageType === 'team' || teamData) {
      response.teamId = teamData.id || null;
      response.teamName = teamData.name;
    } else {
      response.synthId = synthData.id || null;
      response.synthName = synthData.name;
    }

    return new Response(JSON.stringify(response), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('❌ Error in image generation:', error);
    
    return new Response(JSON.stringify({
      error: 'Failed to generate image',
      details: error.message
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
